name: continous-integration

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Inject env file
      run: |
        touch dbr/.env
        echo DATABRICKS_SERVER_HOSTNAME=dbc-4df8c6eb-7aad.cloud.databricks.com >> dbr/.env
        DATABRICKS_HTTP_PATH=/sql/1.0/warehouses/c1a3f6df01a4987c >> dbr/.env
        DATABRICKS_ACCESS_TOKEN=${{ secrets.DATABRICKS_ACCESS_TOKEN }} >> dbr/.env

    - name: Run tests
      run: |
        python -m unittest discover -s tests -p "*.py"